name: Lint

on:
  workflow_call:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  checks: write

jobs:
  lint:
    name: Lint package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m
